# Generated by Django 5.0.1 on 2024-02-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('low', 'низкий'), ('medium', 'средний'), ('high', 'высокий')], max_length=7)),
                ('status', models.CharField(choices=[('planned', 'планируется'), ('process', 'в процессе'), ('done', 'выполнено')], max_length=11)),
            ],
        ),
    ]
